=== unicode-org/message-format-wg/test/schemas/v0-0-1/tests.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/unicode-org/message-format-wg/main/test/schemas/v0-0-1/tests.schema.json",
  "title": "MessageFormat 2 data-driven tests",
  "description": "This is the main schema for MessageFormat 2 test source data.",
  "type": "object",
  "additionalProperties": false,
  "required": [
    "tests"
  ],
  "properties": {
    "scenario": {
      "type": "string",
      "description": "Identifier for the tests in the file"
    },
    "description": {
      "type": "string",
      "description": "Information about the test scenario."
    },
    "defaultTestProperties": {
      "$ref": "#/$defs/defaultTestProperties"
    },
    "tests": {
      "type": "array",
      "items": {
        "$ref": "#/$defs/test"
      },
      "minItems": 1
    }
  },
  "$comment": "This allOf specifies required test properties that allow a default. A value will be required in 'defaultTestProperties' if one is not provided for every individual test.",
  "allOf": [
    {
      "anyOf": [
        {
          "properties": {
            "defaultTestProperties": {
              "required": [
                "locale"
              ]
            }
          }
        },
        {
          "properties": {
            "tests": {
              "type": "array",
              "items": {
                "required": [
                  "locale"
                ]
              }
            }
          }
        }
      ]
    },
    {
      "anyOf": [
        {
          "properties": {
            "defaultTestProperties": {
              "required": [
                "src"
              ]
            }
          }
        },
        {
          "properties": {
            "tests": {
              "type": "array",
              "items": {
                "required": [
                  "src"
                ]
              }
            }
          }
        }
      ]
    },
    {
      "$comment": "Only one assertion is required. It doesn't matter which type.",
      "anyOf": [
        {
          "properties": {
            "defaultTestProperties": {
              "$ref": "#/$defs/anyExp"
            }
          }
        },
        {
          "properties": {
            "tests": {
              "type": "array",
              "items": {
                "$ref": "#/$defs/anyExp"
              }
            }
          }
        }
      ]
    }
  ],
  "$defs": {
    "defaultTestProperties": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "locale": {
          "$ref": "#/$defs/locale"
        },
        "src": {
          "$ref": "#/$defs/src"
        },
        "params": {
          "$ref": "#/$defs/params"
        },
        "exp": {
          "$ref": "#/$defs/exp"
        },
        "expCleanSrc": {
          "$ref": "#/$defs/expCleanSrc"
        },
        "expParts": {
          "$ref": "#/$defs/expParts"
        },
        "expErrors": {
          "$ref": "#/$defs/expErrors"
        }
      }
    },
    "test": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "description": {
          "type": "string",
          "description": "Information about the test."
        },
        "locale": {
          "$ref": "#/$defs/locale"
        },
        "src": {
          "$ref": "#/$defs/src"
        },
        "params": {
          "$ref": "#/$defs/params"
        },
        "exp": {
          "$ref": "#/$defs/exp"
        },
        "expCleanSrc": {
          "$ref": "#/$defs/expCleanSrc"
        },
        "expParts": {
          "$ref": "#/$defs/expParts"
        },
        "expErrors": {
          "$ref": "#/$defs/expErrors"
        },
        "only": {
          "type": "boolean",
          "description": "Normally not set. A flag to use during development to only run one or more specific tests."
        }
      }
    },
    "locale": {
      "description": "The locale to use for formatting.",
      "type": "string"
    },
    "src": {
      "description": "The MF2 syntax source.",
      "$comment": "Array values should be concatenated into a single string. They are only included to help readability in the test JSON.",
      "type": [
        "string",
        "array"
      ],
      "items": {
        "type": "string"
      }
    },
    "params": {
      "description": "Parameters to pass in to the formatter for resolving external variables.",
      "type": "array",
      "items": {
        "$ref": "#/$defs/var"
      }
    },
    "var": {
      "type": "object",
      "oneOf": [
        {
          "additionalProperties": false,
          "required": [
            "name",
            "value"
          ],
          "properties": {
            "name": {
              "type": "string"
            },
            "value": {}
          }
        },
        {
          "required": [
            "name",
            "type",
            "value"
          ],
          "properties": {
            "name": {
              "type": "string"
            },
            "type": {
              "const": "datetime"
            },
            "value": {
              "$comment": "Should be converted to a datetime.",
              "type": "string"
            }
          }
        }
      ]
    },
    "exp": {
      "description": "The expected result of formatting the message to a string.",
      "type": "string"
    },
    "expCleanSrc": {
      "description": "The expected normalized form of `src`, for testing stringifiers.",
      "$comment": "Array values should be concatenated into a single string. They are only included to help readability in the test JSON.",
      "type": [
        "string",
        "array"
      ],
      "items": {
        "type": "string"
      }
    },
    "expParts": {
      "description": "The expected result of formatting the message to parts.",
      "type": "array",
      "items": {
        "oneOf": [
          {
            "description": "Message literal part.",
            "type": "object",
            "additionalProperties": false,
            "required": [
              "type",
              "value"
            ],
            "properties": {
              "type": {
                "const": "literal"
              },
              "value": {
                "type": "string"
              }
            }
          },
          {
            "description": "Message markup part.",
            "type": "object",
            "additionalProperties": false,
            "required": [
              "type",
              "kind",
              "name"
            ],
            "properties": {
              "type": {
                "const": "markup"
              },
              "kind": {
                "enum": [
                  "open",
                  "standalone",
                  "close"
                ]
              },
              "source": {
                "type": "string"
              },
              "name": {
                "type": "string"
              },
              "options": {
                "type": "object"
              }
            }
          },
          {
            "description": "Message expression part.",
            "type": "object",
            "additionalProperties": "false",
            "required": [
              "type",
              "source"
            ],
            "properties": {
              "type": {
                "type": "string"
              },
              "source": {
                "type": "string"
              },
              "locale": {
                "type": "string"
              },
              "parts": {
                "type": "array",
                "items": {
                  "type": "object",
                  "properties": {
                    "type": {
                      "type": "string"
                    },
                    "source": {
                      "type": "string"
                    },
                    "value": {}
                  },
                  "required": [
                    "type"
                  ]
                }
              },
              "value": {}
            }
          }
        ]
      }
    },
    "expErrors": {
      "description": "The runtime errors expected to be emitted when formatting the message. If expErrors is either absent or empty, the message must be formatted without errors.",
      "type": [
        "array",
        "boolean"
      ],
      "items": {
        "type": "object",
        "additionalProperties": false,
        "required": [
          "type"
        ],
        "properties": {
          "type": {
            "enum": [
              "syntax-error",
              "variant-key-mismatch",
              "missing-fallback-variant",
              "missing-selector-annotation",
              "duplicate-declaration",
              "duplicate-option-name",
              "unresolved-variable",
              "unknown-function",
              "unsupported-expression",
              "invalid-expression",
              "operand-mismatch",
              "unsupported-statement",
              "selection-error",
              "formatting-error",
              "bad-input"
            ]
          }
        }
      }
    },
    "anyExp": {
      "anyOf": [
        {
          "required": [
            "exp"
          ]
        },
        {
          "required": [
            "expCleanSrc"
          ]
        },
        {
          "required": [
            "expParts"
          ]
        },
        {
          "required": [
            "expErrors"
          ]
        }
      ]
    }
  }
}

=== unicode-org/message-format-wg/test/tests/syntax.json
{
  "scenario": "Syntax",
  "description": "Test cases that do not depend on any registry definitions.",
  "defaultTestProperties": {
    "locale": "en-US"
  },
  "tests": [
    {
      "src": "hello",
      "exp": "hello"
    },
    {
      "src": "hello {world}",
      "exp": "hello world"
    },
    {
      "src": "hello { world\t\n}",
      "exp": "hello world",
      "expCleanSrc": "hello {world}"
    },
    {
      "src": "hello {\u3000world\r}",
      "exp": "hello world",
      "expCleanSrc": "hello {world}"
    },
    {
      "src": "hello {|world|}",
      "exp": "hello world"
    },
    {
      "src": "hello {||}",
      "exp": "hello "
    },
    {
      "src": "hello {$place}",
      "params": [
        {
          "name": "place",
          "value": "world"
        }
      ],
      "exp": "hello world"
    },
    {
      "src": "hello {$place-.}",
      "params": [
        {
          "name": "place-.",
          "value": "world"
        }
      ],
      "exp": "hello world"
    },
    {
      "src": "hello {$place}",
      "expErrors": [
        {
          "type": "unresolved-variable"
        }
      ],
      "exp": "hello {$place}"
    },
    {
      "src": "{$one} and {$two}",
      "params": [
        {
          "name": "one",
          "value": 1.3
        },
        {
          "name": "two",
          "value": 4.2
        }
      ],
      "exp": "1.3 and 4.2"
    },
    {
      "src": "{$one} et {$two}",
      "locale": "fr",
      "params": [
        {
          "name": "one",
          "value": 1.3
        },
        {
          "name": "two",
          "value": 4.2
        }
      ],
      "exp": "1,3 et 4,2"
    },
    {
      "src": ".local $foo = {bar} {{bar {$foo}}}",
      "exp": "bar bar"
    },
    {
      "src": ".local $foo = {|bar|} {{bar {$foo}}}",
      "exp": "bar bar"
    },
    {
      "src": ".local $foo = {|bar|} {{bar {$foo}}}",
      "params": [
        {
          "name": "foo",
          "value": "foo"
        }
      ],
      "exp": "bar bar"
    },
    {
      "src": ".local $foo = {$bar} {{bar {$foo}}}",
      "params": [
        {
          "name": "bar",
          "value": "foo"
        }
      ],
      "exp": "bar foo"
    },
    {
      "src": ".local $foo = {$baz} .local $bar = {$foo} {{bar {$bar}}}",
      "params": [
        {
          "name": "baz",
          "value": "foo"
        }
      ],
      "exp": "bar foo"
    },
    {
      "src": ".input {$foo} {{bar {$foo}}}",
      "params": [
        {
          "name": "foo",
          "value": "foo"
        }
      ],
      "exp": "bar foo"
    },
    {
      "src": ".input {$foo} .local $bar = {$foo} {{bar {$bar}}}",
      "params": [
        {
          "name": "foo",
          "value": "foo"
        }
      ],
      "exp": "bar foo"
    },
    {
      "src": ".local $foo = {$baz} .local $bar = {$foo} {{bar {$bar}}}",
      "params": [
        {
          "name": "baz",
          "value": "foo"
        }
      ],
      "exp": "bar foo"
    },
    {
      "src": ".local $x = {42} .local $y = {$x} {{{$x} {$y}}}",
      "exp": "42 42"
    },
    {
      "src": "{#tag}",
      "exp": "",
      "expParts": [
        {
          "type": "markup",
          "kind": "open",
          "name": "tag"
        }
      ]
    },
    {
      "src": "{#tag}content",
      "exp": "content",
      "expParts": [
        {
          "type": "markup",
          "kind": "open",
          "name": "tag"
        },
        {
          "type": "literal",
          "value": "content"
        }
      ]
    },
    {
      "src": "{#ns:tag}content{/ns:tag}",
      "exp": "content",
      "expParts": [
        {
          "type": "markup",
          "kind": "open",
          "name": "ns:tag"
        },
        {
          "type": "literal",
          "value": "content"
        },
        {
          "type": "markup",
          "kind": "close",
          "name": "ns:tag"
        }
      ]
    },
    {
      "src": "{/tag}content",
      "exp": "content",
      "expParts": [
        {
          "type": "markup",
          "kind": "close",
          "name": "tag"
        },
        {
          "type": "literal",
          "value": "content"
        }
      ]
    },
    {
      "src": "{#tag foo=bar}",
      "exp": "",
      "expParts": [
        {
          "type": "markup",
          "kind": "open",
          "name": "tag",
          "options": {
            "foo": "bar"
          }
        }
      ]
    },
    {
      "src": "{#tag foo=bar/}",
      "expCleanSrc": "{#tag foo=bar /}",
      "exp": "",
      "expParts": [
        {
          "type": "markup",
          "kind": "standalone",
          "name": "tag",
          "options": {
            "foo": "bar"
          }
        }
      ]
    },
    {
      "src": "{#tag a:foo=|foo| b:bar=$bar}",
      "params": [
        {
          "name": "bar",
          "value": "b a r"
        }
      ],
      "exp": "",
      "expParts": [
        {
          "type": "markup",
          "kind": "open",
          "name": "tag",
          "options": {
            "a:foo": "foo",
            "b:bar": "b a r"
          }
        }
      ]
    },
    {
      "src": "{/tag foo=bar}",
      "exp": "",
      "expParts": [
        {
          "type": "markup",
          "kind": "close",
          "name": "tag",
          "options": {
            "foo": "bar"
          }
        }
      ]
    },
    {
      "src": "{42 @foo @bar=13}",
      "exp": "42",
      "expParts": [
        {
          "type": "string",
          "source": "|42|",
          "value": "42"
        }
      ]
    },
    {
      "src": "{42 @foo=$bar}",
      "exp": "42",
      "expParts": [
        {
          "type": "string",
          "source": "|42|",
          "value": "42"
        }
      ]
    },
    {
      "src": "foo {+reserved}",
      "exp": "foo {+}",
      "expParts": [
        {
          "type": "literal",
          "value": "foo "
        },
        {
          "type": "fallback",
          "source": "+"
        }
      ],
      "expErrors": [
        {
          "type": "unsupported-expression"
        }
      ]
    },
    {
      "src": "foo {&private}",
      "exp": "foo {&}",
      "expParts": [
        {
          "type": "literal",
          "value": "foo "
        },
        {
          "type": "fallback",
          "source": "&"
        }
      ],
      "expErrors": [
        {
          "type": "unsupported-expression"
        }
      ]
    },
    {
      "src": "foo {?reserved @a @b=$c}",
      "exp": "foo {?}",
      "expParts": [
        {
          "type": "literal",
          "value": "foo "
        },
        {
          "type": "fallback",
          "source": "?"
        }
      ],
      "expErrors": [
        {
          "type": "unsupported-expression"
        }
      ]
    },
    {
      "src": ".foo {42} {{bar}}",
      "exp": "bar",
      "expParts": [
        {
          "type": "literal",
          "value": "bar"
        }
      ],
      "expErrors": [
        {
          "type": "unsupported-statement"
        }
      ]
    },
    {
      "src": ".foo{42}{{bar}}",
      "expCleanSrc": ".foo {42} {{bar}}",
      "exp": "bar",
      "expParts": [
        {
          "type": "literal",
          "value": "bar"
        }
      ],
      "expErrors": [
        {
          "type": "unsupported-statement"
        }
      ]
    },
    {
      "src": ".foo |}lit{| {42}{{bar}}",
      "expCleanSrc": ".foo |}lit{| {42} {{bar}}",
      "exp": "bar",
      "expParts": [
        {
          "type": "literal",
          "value": "bar"
        }
      ],
      "expErrors": [
        {
          "type": "unsupported-statement"
        }
      ]
    },
    {
      "src": "{{trailing whitespace}} \n",
      "expCleanSrc": "trailing whitespace",
      "exp": "trailing whitespace"
    }
  ]
}
